In [2]:
import numpy as np

### 1. Import numpy as np and see the version

1. Q. Import numpy as np and print the version number.

In [1]:
import numpy as np
print (np.__version__)


1.18.1


### 2. How to create a 1D array?

2. Q. Create a 1D array of numbers from 0 to 9
#### array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import numpy as np
A= np.arange(0, 9)
print("array from 0 to 9:")
print(A)

array from 0 to 9:
[0 1 2 3 4 5 6 7 8]


### 3. How to create a boolean array?

3. Q. Create a 3×3 numpy array of all True’s

In [24]:
import numpy as np
A = np.array([3,3, True], dtype= bool)
print(A)

[ True  True  True]


### 4. How to extract items that satisfy a given condition from 1D array?

4. Q. Extract all odd numbers from arr  
##### Input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
##### Desired output: #> array([1, 3, 5, 7, 9])

In [60]:
import numpy as np
A = np.array([0,1,2,3,4,5,6,7,8,9])
A[A % 2 == 1] 
print(A)

[0 1 2 3 4 5 6 7 8 9]


### 5. How to replace items that satisfy a condition with another value in numpy array?

5. Q. Replace all odd numbers in arr with -1  
##### Input: >  arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
##### Desired Output:> array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])


In [27]:
import numpy as np
A= np.array([0,1,2,3,4,5,6,7,8,9])
A[A % 2 == 1] = -1
print(A)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 6. How to replace items that satisfy a condition without affecting the original array?

6. Q. Replace all even numbers in arr with 0 without changing arr
##### Input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
##### out>  array([ 0, 0,  2, 0,  4, 0,  6, 0,  8, 0])


In [28]:
import numpy as np
B = np.array([0,1,2,3,4,5,6,7,8,9])
B[B % 2 == 1] = 0
print(B)

[0 0 2 0 4 0 6 0 8 0]


### 7. How to reshape an array?
7. Q. Convert a 1D array to a 2D array with 2 rows
##### Input: np.arange(10)
#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
##### Desired Output:
#> array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])


In [37]:
import numpy as np
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 8. How to stack two arrays vertically?
8. Q. Stack arrays a and b vertically
Input  
a = np.arange(10).reshape(2,-1)  
b = np.repeat(1, 10).reshape(2,-1)  
Desired Output:  
#> array([[0, 1, 2, 3, 4],  
#>        [5, 6, 7, 8, 9],  
#>        [1, 1, 1, 1, 1],  
#>        [1, 1, 1, 1, 1]])


In [54]:
##import numpy as np
A = np.arange(10).reshape(2, -1)
B = np.repeat(1, 10).reshape(2, -1)
np.concatenate([A, B], axis=0)
np.vstack([A, B])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 9. How to stack two arrays horizontally?
9. Q. Stack the arrays a and b horizontally.
##### Input  
a = np.arange(10).reshape(2,-1)  
b = np.repeat(1, 10).reshape(2,-1)  
##### Desired Output:  
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],  
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])


In [56]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
np.concatenate([a, b], axis= 1)
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 10. How to generate custom sequences in numpy without hardcoding?
1. Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
##### Input:  
a = np.array([1,2,3])
##### Desired Output:  
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [64]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### 11. How to get the common items between two python numpy arrays?
11. Q. Get the common items between a and b
#### Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])  
b = np.array([7,2,10,2,7,4,9,4,9,8])
##### Desired Output:
array([2, 4])


In [75]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

### 12. How to remove from one array those items that exist in another?
12. Q. From array a remove all items present in array b

##### Input:
a = np.array([1,2,3,4,5])  
b = np.array([5,6,7,8,9])
##### Desired Output:  
array([1,2,3,4])


In [81]:
a = np.array([1,2,3,4,5])
b =np.array([5,6,7,8,9])
np.delete(a, b)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: in the future out of bounds indices will raise an error instead of being ignored by `numpy.delete`.
  This is separate from the ipykernel package so we can avoid doing imports until


array([1, 2, 3, 4, 5])

### 13. How to get the positions where elements of two arrays match?
13. Q. Get the positions where elements of a and b match
##### Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])  
b = np.array([7,2,10,2,7,4,9,4,9,8])
##### Desired Output:
#> array([1, 3, 5, 7])


In [82]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

### 14. How to extract all numbers between a given range from a numpy array?
14. Q. Get all items between 5 and 10 from a.

##### Input:
a = np.array([2, 6, 1, 9, 10, 3, 27])
###### Desired Output:

#> array([6, 9, 10])

### 15. How to make a python function that handles scalars to work on numpy arrays?
15. Q. Convert the function maxx that works on two scalars, to work on two arrays.

##### Input:

In [19]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)



5

###### Desired Output:
a = np.array([5, 7, 9, 8, 6, 4, 5])  
b = np.array([6, 3, 4, 8, 9, 7, 1])  
pair_max(a, b)  
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

### 16. How to swap two columns in a 2d numpy array?
16.Q. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
arr


In [18]:
import numpy as np
arr = np.arange(9).reshape(3,3)
arr[[1,2,0], :]

array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

### 17. How to swap two rows in a 2d numpy array?
17.Q. Swap rows 1 and 2 in the array arr:

arr = np.arange(9).reshape(3,3)  
arr



In [1]:
import geopandas as gpd

ModuleNotFoundError: No module named 'geopandas'

In [19]:
import numpy as np
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])